services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: to-do-list-spring-boot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge